E_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop_app.urls')),
    path('account/', include('login_app.urls')),
    path('shop/', include('order_app.urls')),
    path('payment/', include('payment_app.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order_app/urls.py
from django.urls import path
from order_app import views
app_name = 'order_app'

urlpatterns = [
    path('add/<pk>/',views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove_cart_item/<pk>/', views.remove_cart_item, name='remove'),
    path('item_increase/<pk>/', views.item_increase, name = 'increase'),
    path('item_decrease/<pk>/', views.item_decrease, name = 'decrease'),
]

shop_app/urls.py
from django.urls import path
from shop_app import views

app_name = 'shop_app'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetails.as_view(), name='product_detail'),
]

shop_app/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural = 'Categories'

class Product(models.Model):
    mainimage = models.ImageField(upload_to='products')
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category,on_delete=models.CASCADE, related_name='category')
    preview_text = models.TextField(max_length=200, verbose_name='Preview_text')
    detail_text = models.TextField(max_length=1000, verbose_name = 'Description')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    class Meta:
        ordering = ['-created']

shop_app/views.py
from django.shortcuts import render
from shop_app.models import Product, Category
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
class Home(ListView):
    model = Product
    template_name = 'shop_app/home.html'

class ProductDetails(DetailView, LoginRequiredMixin):
    context_object_name = 'product'
    model = Product
    template_name = 'shop_app/product_detail.html'

templates/shop_app/home.html
{% extends 'base.html'%}

{% block body_block %}
<div class="container my-5">
  <h2 class="my-5">Feature Products</h2>
  <div class="row">
    {% for product in object_list %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product">
        <div class="image-wrap">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"><a href="{% url 'shop_app:product_detail' pk=product.pk%}">{{product.name}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
              <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
            </div>
          </div>
        </figcaption>
      </figure>

    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/shop_app/product_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
  <div class="card">
    <div class="row">
      <aside class="col-sm-5 border-right">
        <article class="gallery-wrap">
          <div class="img-big-wrap">
            <div>
              <a href="#"><img src="/media/{{product.mainimage}}" style="width:450px;"></a>
            </div>
          </div>
        </article>
      </aside>
      <aside class="col-sm-7">
        <article class="card-body p-5">
          <h3 class="title mp-3">{{product.name}}</h3>
          <p class="price-detail-wrap">
            <span class="price h3 text-warning">
              <span class="currency">BDT &#2547;</span><span class="num">{{product.price}}</span>
            </span>
          </p>
          <dl class="item-property">
            <dt>Description</dt>
            <dd>
              <p>{{product.detail_text}}</p>
            </dd>
          </dl>
          <a href="{% url 'order_app:add' pk=product.pk %}" class="btn btn-lg btn-outline-primary text-uppercase"><i class="fas fa-shopping-cart"></i> Add To Cart</a>
        </article>
      </aside>
    </div>
  </div>
</div>
{% endblock %}