E_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop_app.urls')),
    path('account/', include('login_app.urls')),
    path('shop/', include('order_app.urls')),
    path('payment/', include('payment_app.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login_app/urls.py
from django.urls import path
from login_app import views
app_name = 'login_app'

urlpatterns = [
    path('signup/',views.Sign_UP, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name = 'profile'),

]

order_app/urls.py
from django.urls import path
from order_app import views
app_name = 'order_app'

urlpatterns = [
    path('add/<pk>/',views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove_cart_item/<pk>/', views.remove_cart_item, name='remove'),
    path('item_increase/<pk>/', views.item_increase, name = 'increase'),
    path('item_decrease/<pk>/', views.item_decrease, name = 'decrease'),
]

shop_app/urls.py
from django.urls import path
from shop_app import views

app_name = 'shop_app'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetails.as_view(), name='product_detail'),
]

templates/base.html
  {% load static %}
  <!DOCTYPE html>
  <html lang="en" dir="ltr">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
      <link rel="stylesheet" href="{% static 'css/style.css'%}">
      <title>{% block title_block %}E-com | Clinton {% endblock%}</title>
      <style>
        .card{
          height: 350px;
        }
        .card-product:after{
          content: "";
          display: table;
          clear: both;
          visibility: hidden;
        }
        .card-product .price-new, .cart-product .price{
          margin-right: 5px;
        }
        .card-product .price-old{
          color: #999;
        }
        .card-product .image-wrap{
          border-radius: 3px 3px 0 0;
          overflow: hidden;
          height: 220px;
          position: relative;
          text-align: center;
        }
        .card-product .image-wrap img{
          max-height: 100%;
          max-width: 100%;
          object-fit: cover;
        }
        .card-product .info-wrap{
          overflow: hidden;
          padding: 15px;
          border-top: 1px solid #eee;
        }
        .card-product .action-wrap{
          padding-top: 4px;
          margin-top: 4px;
        }
        .card-product .bottom-wrap{
          padding: 15px;
          border-top: 1px solid #eee;
        }
        .card-product .title{
          margin-top: 0px;
        }
      </style>
    </head>
    <body>
      {% include 'nav.html'%}
      <div class="container">

        <div class="messages container mt-2">
          {% if messages %}
          {% for message in messages%}
          <div {% if message.tags %}class="alert alert-{{message.tags}} {% endif %}" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label='Close'><span aria-hidden="true">&times;</span></button>
          </div>
          {% endfor %}
          {% endif %}
        </div>

        {% block body_block%}

        {% endblock%}

      </div>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
  </html>

templates/nav.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a href="{% url 'shop_app:home'%}" class="navbar-brand">Easy Brand</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav ml-auto">
    {% if request.user.is_authenticated %}
    <li class="nav-item">
      <a href="{% url 'order_app:cart'%}" class="nav-link">
        <i class="fa fa-shopping-cart"></i> Cart
        <span class="badge badge-light">{{request.user | cart_total }}</span>
      </a>

    </li>
    <li class="nav-item dropdown">
      <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i> {{request.user.profile.username}}</a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'login_app:profile'%}">Profile</a>
        <a class="dropdown-item">Order</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'login_app:logout'%}">Logout</a>
      </div>
    </li>
    {%else%}
    <li class="nav-item">
      <a href="{% url 'login_app:login'%}" class="btn btn-primary">Login</a>
    </li>
    {%endif%}
  </ul>
</div>
  </div>
</nav>